#// VERBOSE: True

MODEL:
  SESSION: 'RDD_Kligler'  # Define your current task here

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 30
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 512
  PS_H: 512
  TRAIN_DIR: 'Kligler\train' # path to training data
  VAL_DIR: 'Kligler\train'    # path to validation data
  SAVE_DIR: 'checkpoints'     # path to save models and images
  ORI: True

TESTING:
  WEIGHT: './checkpoints/RDD_epoch_18.pth'
  SAVE_IMAGES: True